### PR TITLE
feat: adds a version map url setting

### PR DESCRIPTION
**Pull request by OlshaMB**
Adds ability to use custom version map url.
## Why implement it?
I need this because many libs use mach version channel and won't compile with the latest.

### CODE REVIEW

**Comment by OlshaMB** [comment]
I need to fix one bug before merging

**Comment by tristanisham** [comment]
No problem. I haven’t started looking at it yet. One thing, please make
sure your PR fits the new contributing guidelines at ./CONTRIBUTING.md.

**Comment by OlshaMB** [comment]
I fixed the bug(details in commit).
I can also migrate `-D=zls` and `install version` to my `plannedSkips`, but I think this should be separate pr. But at the same time i don't want to separate the lines and make a separate pr(That is not worth the time). Also I am not fixing the `zls` for `mach-latest` or other names as there is a large rewrite and in separate pr incomming.

**Review by tristanisham — APPROVED** [review]
Tweaked how your command worked, changed the flag, added validation, and will need to tweak some more. Like adding better error messages. Still, great PR.

**Comment by OlshaMB** [comment]
@tristanisham Did you remove this flag?

**Pull request merged**
